version: '3.4'
services:
  database:
    container_name: database
    restart: always
    env_file: 
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
      target: database
    ports:
      - 5432:5432
  model:
    container_name: staley_model
    depends_on:
      - database
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
      target: model